# Generated by Django 5.2.5 on 2025-09-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_furniture'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='Group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='packing.group'),
            preserve_default=False,
        ),
    ]
