# Generated by Django 5.2.5 on 2025-09-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_furniture_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='slug',
        ),
    ]
