# Generated by Django 5.2.5 on 2025-09-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_rename_name_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slug',
            new_name='name',
        ),
    ]
